### ISSUE TITLE
use ae_plugin

### ISSUE THREAD

**Issue by grw-rs** [aeternity/ae-channel-service#50]
There's now ae_plugin repository here: https://github.com/aeternity/ae_plugin which solves integration of AE node and Elixir.

It would be good to stick to common integration mechanism which can glue AE node and any further Elixir functionality on top of AE node.

Another motivation is to find out what else is missing in AE plugin for it to be used more conveniently.

**Comment by Artur64** [comment]
Closing this issue, for future investigation and clarification.
