### ISSUE TITLE
[warn] problem opening file {:error, {:file_error, [error] Could not start node watcher...

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/ae-channel-service#93]
Hey, firing up the latest `master` with ```AE_NODE_URL="wss://95.216.27.196:443/channel" AE_NODE_NETWORK_ID="ae_channel_service_test" iex -S mix phx.server ```
. I am seeing this:

```
[info] File_name when listing channels is "/Users/ethereumbook/Documents/DAPPS/Aeternity/ae-channel-service/data/responder_ak_cFBreUSVWPEc3qSCYHfcy5yW2CWkbdrPkr9itgQfBw1Zdd6HV"
[warn] problem opening file {:error, {:file_error, 'data/responder_ak_cFBreUSVWPEc3qSCYHfcy5yW2CWkbdrPkr9itgQfBw1Zdd6HV', :enoent}}
[info] Running AeChannelInterfaceWeb.Endpoint with cowboy 2.7.0 at 0.0.0.0:4000 (http)
[error] Could not start node watcher because script "/Users/ethereumbook/Documents/DAPPS/Aeternity/ae-channel-service/apps/ae_channel_interface/assets/node_modules/webpack/bin/webpack.js" does not exist. Your Phoenix application is still running, however assets won't be compiled. You may fix this by running "cd assets && npm install".
[info] Access AeChannelInterfaceWeb.Endpoint at http://localhost:4000
```

**Comment by AleksandarFilipov** [comment]
This is just a warning message which should not affect anything. Once you have a running client you should get the `data` folder with the propriate file.

**Comment by nikita-fuchs** [comment]
Can something be done about the [Error] ? One has to manually enter that dir and run `npm install`

**Comment by AleksandarFilipov** [comment]
as documented here :) https://github.com/aeternity/ae-channel-service/#build

_to get the user interface look sane you could also:
cd apps/ae_channel_interface/assets && npm install && cd -_

btw, i think it's done automatically i you do `make clean deps` as documented, se here https://github.com/aeternity/ae-channel-service/blob/contract-interaction/Makefile#L15

**Comment by nikita-fuchs** [comment]
Thanks @AleksandarFilipov , I didn't see that in the setup instructions circulating in our devchat. This used to work automatically some time ago indeed, but now I have to do it manually for some reason?

**Comment by AleksandarFilipov** [comment]
Well it was never done automatically. But now i think it is :)
